run:
  go: "1.17.8"

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - revive
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - misspell
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  ifshort:
    max-decl-chars: 100
    max-decl-lines: 10
